day1p1: day1p1.c
	gcc $@.c -o $@

test_p1: day1p1 test.txt
	cat test.txt | ./day1p1

run_p1: day1p1 input.txt
	cat input.txt | ./day1p1

day1p2: day1p2.c
	gcc $@.c -o $@

test_p2: day1p2 test.txt
	cat test.txt | ./day1p2

run_p2: day1p2 input.txt
	cat input.txt | ./day1p2
