GUILE=guile -s

test:
	@echo part1 | cat - test.txt | $(GUILE) day5.scm
	@echo part2 | cat - test.txt | $(GUILE) day5.scm

run:
	@echo part1 | cat - input.txt | $(GUILE) day5.scm
	@echo part2 | cat - input.txt | $(GUILE) day5.scm
